export const BASKET_ADD_ITEM = "BASKET_ADD_ITEM";
export const BASKET_REMOVE_ITEM = "BASKET_REMOVE_ITEM";
export const BASKET_CHANGE_QUANTITY = "BASKET_CHANGE_QUANTITY";
export const BASKET_RELOAD = "BASKET_RELOAD";
